# Generated by Django 4.1 on 2024-05-07 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_task_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
